### ISSUE TITLE
Anki Crashes when update is installed

### ISSUE THREAD

**Issue by sebastianrueckerai** [zjosua/anki-mc#118]
#### Describe the bug
Anki Crashes when I install the addon

#### To Reproduce
1. Install the addon
2. Restart Anki

#### Expected behavior
Not to crash! :)

#### Information about your set-up

On which platform(s) does the error occur?
- [ ] Ankiweb
- [X ] Desktop: *type your OS including version here*
- [ ] Mobile: *type your OS including version here*

#### Additional context
Output:

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 6.6.0 PyQt 6.6.0
Platform: Windows-10-10.0.19045
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-11-12 16:09:40
Add-ons possibly involved: ⁨Multiple Choice for Anki⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.progress", line 118, in handler
  File "aqt.main", line 218, in on_window_init
  File "aqt.main", line 265, in setupProfileAfterWebviewsLoaded
  File "aqt.main", line 317, in setupProfile
  File "aqt.main", line 496, in loadProfile
  File "_aqt.hooks", line 4101, in __call__
  File "C:\Users\XXX\AppData\Roaming\Anki2\addons21\1566095810\template.py", line 257, in manage_multiple_choice_note_type
    AddOrUpdateModel()
  File "C:\Users\XXX\AppData\Roaming\Anki2\addons21\1566095810\template.py", line 244, in AddOrUpdateModel
    addModel(mw.col)
  File "C:\Users\XXX\AppData\Roaming\Anki2\addons21\1566095810\template.py", line 202, in addModel
    fillTemplateAndModelFromFile(model)
  File "C:\Users\XXX\AppData\Roaming\Anki2\addons21\1566095810\template.py", line 145, in fillTemplateAndModelFromFile
    set_front_template(model, front_template)
  File "C:\Users\XXX\AppData\Roaming\Anki2\addons21\1566095810\template.py", line 313, in set_front_template
    model["tmpls"][0]["qfmt"] = template_text
IndexError: list index out of range

**Comment by 3ter** [comment]
Thank you for the report.

The stack trace suggests that you had no Multiple Choice model prior to the addon installation.
I just **verified** this. To reproduce I removed the note type from my note types, downgraded the addon version and the crash happens like above.

Do you want to do it @zjosua or shall I 😃 ?

**Comment by Jorgedrc** [comment]
Tengo el mismo problema "Error 
Se ha producido un error. Por favor inicia la Anki manteniendo presionadas ples teclas Mayús y la flecha hacia abajo, lo que desactivará temporalmente los extensiones que tienes instaladas. 
Si este error persiste sólo cuando tienes las extensiones activadas, utiliza Herramientas > Menú de Extensiones para deshabilitar alguna extensión y reinicia el Anki, repitiendo este proceso hasta que descubras qué extensión en concreto es la que causa el problema 
Cuando hayas descubierto la extensión que causaba el problema, por favor informa de esto a [sitio de soporte de extensiones](https://forums.ankiweb.net/c/add-ons/11). 
Información de depuración:
Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 6.6.0 PyQt 6.6.0
Platform: Windows-10-10.0.19041
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-11-13 18:22:50
Complementos posiblemente implicados: ⁨Multiple Choice for Anki⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.progress", line 118, in handler
  File "aqt.main", line 218, in on_window_init
  File "aqt.main", line 265, in setupProfileAfterWebviewsLoaded
  File "aqt.main", line 317, in setupProfile
  File "aqt.main", line 496, in loadProfile
  File "_aqt.hooks", line 4101, in __call__
  File "C:\Users\USER\AppData\Roaming\Anki2\addons21\1566095810\template.py", line 257, in manage_multiple_choice_note_type
    AddOrUpdateModel()
  File "C:\Users\USER\AppData\Roaming\Anki2\addons21\1566095810\template.py", line 244, in AddOrUpdateModel
    addModel(mw.col)
  File "C:\Users\USER\AppData\Roaming\Anki2\addons21\1566095810\template.py", line 202, in addModel
    fillTemplateAndModelFromFile(model)
  File "C:\Users\USER\AppData\Roaming\Anki2\addons21\1566095810\template.py", line 145, in fillTemplateAndModelFromFile
    set_front_template(model, front_template)
  File "C:\Users\USER\AppData\Roaming\Anki2\addons21\1566095810\template.py", line 313, in set_front_template
    model["tmpls"][0]["qfmt"] = template_text
IndexError: list index out of range"
Cómo que ningún modelo de opción múltiple antes de la instalación del complemento? Precisamente para tener flashcards de opción múltiple uno descarga el complemento, no entiendo. Tampoco entiendo eso de eliminar el tipo de nota de los tipos de notas, qué notas de donde? Nos podría ayudar por favor? Muchas gracias.

**Comment by zjosua** [comment]
Thank you all for the report and diagnosing.
@3ter, before I release it, do you see any issues with the fix I pushed?

**Comment by 3ter** [comment]
@zjosua That was exactly, what was needed. I tested a bit around with the version but nothing surprising popped up.

**Comment by Jorgedrc** [comment]
O sea se solucionó el problema o no? Se podrá usar el complemento? Yo lo tengo descargado e instalado pero deshabilitado pues el complemento no me permite usar ANKI si está habilitado. Qué debo hacer?
