### ISSUE TITLE
Invalid HTML on card: TypeError: Cannot read property 'innerHTML' of undefined

### ISSUE THREAD

**Issue by avanhulle** [zjosua/anki-mc#25]
When I use this card I get the following error message: 

Invalid HTML on card: TypeError: Cannot read property 'innerHTML' of undefined
TypeError: Cannot read property 'innerHTML' of undefined
at onShuffle (eval at (http://127.0.0.1:6827/_anki/jquery.js:2:2651), :71:111)
at generateTable (eval at (http://127.0.0.1:6827/_anki/jquery.js:2:2651), :32:9)
at eval (eval at (http://127.0.0.1:6827/_anki/jquery.js:2:2651), :130:20)
at eval ()
at http://127.0.0.1:6827/_anki/jquery.js:2:2651
at Function.globalEval (http://127.0.0.1:6827/_anki/jquery.js:2:2662)
at Ha (http://127.0.0.1:6827/_anki/jquery.js:3:21262)
at n.fn.init.append (http://127.0.0.1:6827/_anki/jquery.js:3:22791)
at n.fn.init. (http://127.0.0.1:6827/_anki/jquery.js:3:24070)
at Y (http://127.0.0.1:6827/_anki/jquery.js:3:4515)

Using this on Windows 10 PC. 
On android device the card is showing but I get "Correct answer x%"

**Comment by rdvrd** [comment]
I have the same issue as what you get on android but on both ankidroid as well as windows. I'm not sure why that elment is not being replaced

**Comment by zjosua** [comment]
@avanhulle and @rdvrd is this still a problem with the newest version of the add-on?

**Comment by rdvrd** [comment]
I now have this error on the back card with the new version:
```
Invalid HTML on card: TypeError: Persistence.getItem is not a function
TypeError: Persistence.getItem is not a function
at onLoad (eval at (http://127.0.0.1:51055/_anki/jquery.js:2:2651), :9:52)
at run (eval at (http://127.0.0.1:51055/_anki/jquery.js:2:2651), :95:20)
at eval (eval at (http://127.0.0.1:51055/_anki/jquery.js:2:2651), :115:9)
at eval ()
at http://127.0.0.1:51055/_anki/jquery.js:2:2651
at Function.globalEval (http://127.0.0.1:51055/_anki/jquery.js:2:2662)
at Ha (http://127.0.0.1:51055/_anki/jquery.js:3:21262)
at n.fn.init.append (http://127.0.0.1:51055/_anki/jquery.js:3:22791)
at n.fn.init. (http://127.0.0.1:51055/_anki/jquery.js:3:24070)
at Y (http://127.0.0.1:51055/_anki/jquery.js:3:4515)
```

**Comment by 3ter** [comment]
I've got that error too, but only in the console when debugging and only when viewing the back card with "Manage Note Types...".

With the stacktrace and everything it seems that this is instead a full blown exception for you when reviewing cards. Is this the latest version of anki as well?

When checked in a regular browser (e.g. Chrome) persistence is properly recognized as a function:
![image](https://user-images.githubusercontent.com/11499929/111380506-bb4bd600-86a4-11eb-9a83-ae943c8bdd40.png)

**Comment by 3ter** [comment]
Thanks to @zjosua all dependencies are now included in the release and the update worked fine for me.

Can you @rdvrd or @avanhulle please check if the errors keep quiet now (on anki 2.1.42 / addon 2.4.1)?

**Comment by Estreia18** [comment]
I still get following error message:

Invalid HTML on card: TypeError: Persistence.getItem is not a function
TypeError: Persistence.getItem is not a function
at onLoad (eval at (http://127.0.0.1:56701/_anki/js/vendor/jquery.js:2:2651), :9:52)
at run (eval at (http://127.0.0.1:56701/_anki/js/vendor/jquery.js:2:2651), :95:20)
at eval (eval at (http://127.0.0.1:56701/_anki/js/vendor/jquery.js:2:2651), :115:9)
at eval ()
at http://127.0.0.1:56701/_anki/js/vendor/jquery.js:2:2651
at Function.globalEval (http://127.0.0.1:56701/_anki/js/vendor/jquery.js:2:2662)
at Ha (http://127.0.0.1:56701/_anki/js/vendor/jquery.js:3:21262)
at n.fn.init.append (http://127.0.0.1:56701/_anki/js/vendor/jquery.js:3:22791)
at n.fn.init. (http://127.0.0.1:56701/_anki/js/vendor/jquery.js:3:24070)
at Y (http://127.0.0.1:56701/_anki/js/vendor/jquery.js:3:4515)

**Comment by 3ter** [comment]
I don't really understand why this is triggered on some systems and not another. The error [triggering line is this](https://github.com/ankitects/anki/blob/39c6429fe2f8dfa1c4538900bbb8ed146a6064f0/qt/aqt/data/web/js/reviewer.ts#L59), where the `html` string is put into an `html` function I couldn't find in the anki repo.
```ts
// update text
try {
    qa.html(html);
} catch (error) {
    renderError("HTML")(error);
}
```

**Comment by DarvidTorres** [comment]
Anyone knows how to solve the problem? I can't preview the back side of cards, it shows the same problem:

Invalid HTML on card: TypeError: Persistence.getItem is not a function
TypeError: Persistence.getItem is not a function
at onLoad (eval at (http://127.0.0.1:65396/_anki/jquery.js:2:2651), :30:52)
at run (eval at (http://127.0.0.1:65396/_anki/jquery.js:2:2651), :135:20)
at eval (eval at (http://127.0.0.1:65396/_anki/jquery.js:2:2651), :155:9)
at eval ()
at http://127.0.0.1:65396/_anki/jquery.js:2:2651
at Function.globalEval (http://127.0.0.1:65396/_anki/jquery.js:2:2662)
at Ha (http://127.0.0.1:65396/_anki/jquery.js:3:21262)
at n.fn.init.append (http://127.0.0.1:65396/_anki/jquery.js:3:22791)
at n.fn.init. (http://127.0.0.1:65396/_anki/jquery.js:3:24070)
at Y (http://127.0.0.1:65396/_anki/jquery.js:3:4515)

**Comment by 3ter** [comment]
Previewing now works as expected.
