### ISSUE TITLE
Iam getting this error whenerver I use MCQ type card

### ISSUE THREAD

**Issue by sanketwagh147** [zjosua/anki-mc#60]
Invalid HTML on card: TypeError: Persistence.getItem is not a function
TypeError: Persistence.getItem is not a function
at onLoad (eval at (http://127.0.0.1:56789/_anki/jquery.js:2:2651), :9:52)
at run (eval at (http://127.0.0.1:56789/_anki/jquery.js:2:2651), :95:20)
at eval (eval at (http://127.0.0.1:56789/_anki/jquery.js:2:2651), :115:9)
at eval ()
at http://127.0.0.1:56789/_anki/jquery.js:2:2651
at Function.globalEval (http://127.0.0.1:56789/_anki/jquery.js:2:2662)
at Ha (http://127.0.0.1:56789/_anki/jquery.js:3:21262)
at n.fn.init.append (http://127.0.0.1:56789/_anki/jquery.js:3:22791)
at n.fn.init. (http://127.0.0.1:56789/_anki/jquery.js:3:24070)
at Y (http://127.0.0.1:56789/_anki/jquery.js:3:4515)

**Comment by 3ter** [comment]
This most probably has been resolved with the new version of the addon.
