### ISSUE TITLE
Error Code with Ankimc

### ISSUE THREAD

**Issue by Kothira** [zjosua/anki-mc#84]
**If you are about to request a different color coding, consider coding it yourself and submitting it as a pull request. Most likely I will not reply to requests for different color coding if they are submitted as an issue.**

**Is your feature request related to a problem? Please describe.**
I have an error code appear every instance I run Anki on desktop. I have not tried on other devices as I only create cards on pc. (Error code copied in full at bottom.)

**Describe the solution you'd like**
No more error code when I start Anki desktop.

**Describe alternatives you've considered**
I already worked with a member of Anki support staff. They suggested creating this issue here.

**Additional context**
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-07-28 20:01:27

Caught exception:
Traceback (most recent call last):
  File "aqt\progress.py", line 54, in handler
  File "aqt\main.py", line 149, in on_window_init
  File "aqt\main.py", line 197, in setupProfileAfterWebviewsLoaded
  File "aqt\main.py", line 244, in setupProfile
  File "aqt\main.py", line 425, in loadProfile
  File "aqt\hooks_gen.py", line 2979, in __call__
  File "C:\Users\kothi\AppData\Roaming\Anki2\addons21\1566095810\__init__.py", line 56, in delayedInit
    getOrCreateModel()
  File "C:\Users\kothi\AppData\Roaming\Anki2\addons21\1566095810\__init__.py", line 49, in getOrCreateModel
    return updateTemplate(mw.col)
  File "C:\Users\kothi\AppData\Roaming\Anki2\addons21\1566095810\template.py", line 560, in updateTemplate
    col.models.save(model)
  File "anki\models.py", line 556, in save
  File "anki\models.py", line 539, in update
  File "anki\_backend\generated.py", line 450, in add_or_update_notetype
  File "anki\_backend\__init__.py", line 131, in _run_command
anki.errors.TemplateError: Card template ⁨1⁩ in notetype '⁨AllInOne (kprim, mc, sc)⁩' has a problem.<br>See the preview for more information.

**Comment by jeremy-browne** [comment]
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-07-31 14:40:15

Caught exception:
Traceback (most recent call last):
  File "aqt.progress", line 118, in handler
  File "aqt.main", line 197, in on_window_init
  File "aqt.main", line 243, in setupProfileAfterWebviewsLoaded
  File "aqt.main", line 290, in setupProfile
  File "aqt.main", line 470, in loadProfile
  File "aqt.hooks_gen", line 3244, in __call__
  File "C:\Users\jerem\AppData\Roaming\Anki2\addons21\1566095810\__init__.py", line 56, in delayedInit
    getOrCreateModel()
  File "C:\Users\jerem\AppData\Roaming\Anki2\addons21\1566095810\__init__.py", line 49, in getOrCreateModel
    return updateTemplate(mw.col)
  File "C:\Users\jerem\AppData\Roaming\Anki2\addons21\1566095810\template.py", line 560, in updateTemplate
    col.models.save(model)
  File "anki.models", line 559, in save
  File "anki.models", line 542, in update
  File "anki._backend.generated", line 861, in add_or_update_notetype
  File "anki._backend", line 146, in _run_command
anki.errors.CardTypeError: Card template ⁨1⁩ in notetype '⁨AllInOne (kprim, mc, sc)⁩' has a problem.<br>See the preview for more information.

I am getting this as well

**Comment by 3ter** [comment]
Couldn't reproduce with Anki 2.1.54 and the latest addon version from Ankiweb.
