### ISSUE TITLE
Error when editing other add-ons' config

### ISSUE THREAD

**Issue by zjosua** [zjosua/anki-mc#94]
#### Describe the bug
anki-mc tries to update the coloring options in the card template every time an add-on config is changed.

```
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.55 (dev) Python 3.9.10 Qt 6.4.0 PyQt 6.4.0
Platform: Linux-6.0.8-surface-x86_64-with-glibc2.31
Flags: frz=False ao=True sv=2
Add-ons, last update check: 2022-11-20 12:07:06
Add-ons possibly involved: ⁨Multiple Choice⁩

Caught exception:
Traceback (most recent call last):
  File "/home/zjosua/.cache/bazel/_bazel_zjosua/1c79c7ac51bf6692c8fc3f9a9a4ef48a/execroot/ankidesktop/bazel-out/k8-fastbuild/bin/qt/runanki.runfiles/ankidesktop/qt/aqt/addons.py", line 1604, in accept
    txt = gui_hooks.addon_config_editor_will_save_json(txt)
  File "/home/zjosua/.cache/bazel/_bazel_zjosua/1c79c7ac51bf6692c8fc3f9a9a4ef48a/execroot/ankidesktop/bazel-out/k8-fastbuild/bin/qt/runanki.runfiles/ankidesktop/qt/aqt/hooks_gen.py", line 349, in __call__
    text = filter(text)
  File "/home/zjosua/.local/share/Anki2/addons21/multiple_choice/template.py", line 167, in update_multiple_choice_note_type_from_config
    updateTemplate(mw.col, user_config_dict)
  File "/home/zjosua/.local/share/Anki2/addons21/multiple_choice/template.py", line 135, in updateTemplate
    fillTemplateAndModelFromFile(template, model, user_config)
  File "/home/zjosua/.local/share/Anki2/addons21/multiple_choice/template.py", line 95, in fillTemplateAndModelFromFile
    options_java_script = getOptionsJavaScriptFromConfig(user_config)
  File "/home/zjosua/.local/share/Anki2/addons21/multiple_choice/template.py", line 78, in getOptionsJavaScriptFromConfig
    f"        colorize: {'true' if user_config['colorQuestionTable'] else 'false'},\n"
KeyError: 'colorQuestionTable'
```

#### To Reproduce
1. Edit the config of another add-on
2. Error occurs when saving the config

#### Expected behavior
anki-mc ignores the edit of other add-on's config

#### What have you tried?
- Thinking. Brain tells me this was most likely introduced in f0a6bf2fea39d3a6bf17ea3b8a40b21c19b50f32. Can't be bothered to fix it now though, as I'm working on another add-on.

#### Information about your set-up

On which platform(s) does the error occur?
- [ ] Ankiweb
- [x] Desktop: Debian bullseye
- [ ] Mobile

Debug info:
```
    
    Anki 2.1.55 (dev) Python 3.9.10 Qt 6.4.0 PyQt 6.4.0
    Platform: Linux-6.0.8-surface-x86_64-with-glibc2.31
    Flags: frz=False ao=True sv=2
    Add-ons, last update check: 2022-11-20 12:07:06
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    '' ['right_hand_reviews', 0, 'None', mod]
    Add Hyperlink ['318752047', 2022-05-23T15:16, 'None', '']
    Anki Simulator ['817108664', 2021-08-07T21:24, 'None', '']
    AnkiWebView Inspector ['31746032', 2022-04-08T21:44, 'None', '']
    Batch Editing ['291119185', 2019-06-17T17:52, 'None', '']
    Cloze Overlapper ['cloze_overlapper', 2019-08-11T08:03, 'None', '']
    Extended Card Stats During Review ['1008566916', 2018-10-03T14:53, 'None', '']
    Extended Schema Hash ['1187737890', 2020-01-21T11:59, 'None', '']
    Field History ['1247884413', 2019-01-08T19:34, 'None', mod]
    Highlight Search Results in the Browser ['highlight_search_results', 2020-05-05T02:19, 'None', '']
    Image Occlusion Enhanced ['image_occlusion_enhanced', 2022-04-09T08:55, 'None', '']
    Leaderboard ['41708974', 2022-05-12T11:46, 'None', mod]
    Mini Format Pack ['mini_format_pack', 2019-08-12T09:37, 'None', '']
    Multiple Choice ['multiple_choice', 2022-10-31T09:48, 'None', mod]
    Picmonic Anki Add-On ['40737180', 2022-06-14T23:35, 'None', mod]
    Pokémanki ['pokemanki', 2022-11-17T08:06, 'None', '']
    Pop-up Dictionary ['popup_dictionary', 2019-10-18T20:28, 'None', '']
    Puppy Reinforcement ['puppy_reinforcement', 2019-08-11T08:20, 'None', '']
    Quick tagging 21 ['304770511', 2020-02-11T07:17, 'None', mod]
    Search and Replace Tags ['138501288', 2018-10-01T16:47, 'None', '']
    Speed Focus Mode ['speed_focus_mode', 2022-11-16T18:09, 'None', '']
    Spell Checker with Custom Dictionaries ['spell_checker', 2022-11-20T20:15, 'None', mod]
    Symbols As You Type ['2040501954', 2022-06-08T06:09, 'None', '']
    Symbols ['1461102936', 2019-06-17T17:52, 'None', mod]
    Visual Feedback for Reviews ['review_feedback', 2020-01-28T21:30, 'None', '']
    gTTS text to speech support ['391644525', 2020-03-15T00:38, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1008566916 1187737890 1247884413 138501288 1461102936 2040501954 291119185 304770511 31746032 318752047 391644525 40737180 41708974 817108664
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    '' ['print_as_flashcards', 0, 'None', '']
    AMBOSS add-on ['0amboss_addon', 2022-01-19T21:42, 'None', mod]
    Anki Habitica for 21 ['1758045507', 2022-02-09T13:54, 'None', mod]
    Spell Check ['spell_check', 2022-09-10T09:39, 'None', '']
    Spelling Police ['spelling_police', 2021-02-19T00:23, 'None', mod]
    Trigger and actions change one card depending on what occurs on another card ['1981494159', 2021-10-18T10:32, 'None', mod]
```

**Comment by 3ter** [comment]
Good find and quick solution! I know too little of those Anki hooks it seems 😅.

In a future refactoring I would add a check for the package `__name__` (which is the name of the addon as used in https://github.com/zjosua/anki-mc/blob/bb959ac6afcae81df3280f7cbfd88a0a12c1cf54/src/multiple_choice/template.py#L91) instead of the dict keys (though I pondered with the idea of a "sane config" check (and not closing the config screen until a proper config has been set).

**Comment by zjosua** [comment]
This would not work, as `__name__` will always refer to our add-on.
Read [here](https://www.geeksforgeeks.org/__name__-a-special-variable-in-python/) or try this:
```python
def update_multiple_choice_note_type_from_config(user_config: str):
    """Set options according to saved user's meta.json in the addon's folder"""
    user_config_dict = json.loads(user_config)
    print(f"addon: {mw.addonManager.addonFromModule(__name__)}")
    # Editing other add-ons' config also runs this hook.
    # Only update if the config matches anki-mc's config.
    if list(user_config_dict.keys()) == [
        "answerColoring",
        "colorAnswerTable",
        "colorQuestionTable",
        "hideAnswerTable",
    ]:
        updateTemplate(mw.col, user_config_dict)
    return user_config
```

I would probably make sense to make a PR to modify the hook so that it gets the name of the edited add-on.
